extends:
  - '@oacore/eslint-config-react'

parser: babel-eslint
env:
  browser: true
settings:
  import/resolver:
    node:
      paths: ['./src']
      extensions: ['.js', '.jsx']

overrides:
  - files: ['*.config.js']
    env:
      browser: false
      node: true
    rules:
      import/no-extraneous-dependencies: [error, { devDependencies: true }]
