extends:
  - stylelint-config-twbs-bootstrap/css
  - stylelint-config-css-modules
  - stylelint-prettier/recommended
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules: [extend]
  max-nesting-depth:
    - 3
    - ignore: [blockless-at-rules, pseudo-classes]
